# Site settings
title: neiro Î» Web development, functional programming
email: neiro.mail@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal website, blog and portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://neiro.io" # the base hostname & protocol for your site
twitter: "https://twitter.com/ne1ro"
github: "https://github.com/ne1ro"
linkedin: "https://ru.linkedin.com/in/neiro"

# Build settings
markdown: kramdown

exclude:
  - bower.json
  - LICENSE
  - Gemfile
  - Guardile
  - Gemfile.lock
  - vendor

# Jekyll assets configuration
assets:
  js_compressor: uglifier
  css_compressor: sass

navigation:
  - title: Blog
    url: /index.html
  - title: Projects
    url: /projects.html
  - title: About me
    url: /about.html
  - title: Contact
    url: /contact.html
